# Use spaces instead of tabs
# sane defaults for CLI arguments 
executor: slurm
jobs: 5000
cores: 100
software-deployment-method: conda
immediate-submit: false
notemp: true
restart-times: 0
max-jobs-per-second: 10
max-status-checks-per-second: 10
latency-wait: 120
keep-going: true
rerun-incomplete: true
printshellcmds: true
show-failed-logs: true


# SLURM
# Note that raw string arguments need double quotes (see slurm_extra)
# Slurm parition and qos must match on the CeMM cluster.
default-resources:
    # slurm_account, partition, and runtime are recommended.
    # match the CeMM intranet: https://cemmat.sharepoint.com/sites/IT-Resources/SitePages/Submitting-Slurm-Jobs.aspx
    slurm_account: lab_bock
    slurm_partition: tinyq
    slurm_extra: "'--qos=tinyq'" # Note the extra quoting!
    runtime: 120 # in minutes
#     --kill-on-invalid-dep=yes # could be added to slurm_extra in case of immediate-submit: true
